### ISSUE TITLE
Unable to determine Swift version for the following pod

### ISSUE THREAD

**Issue by 12366** [Apurv2017/audioRecorder2#5]
- `audio_recorder2` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod

**Comment by apurvh** [comment]
@12366 have you tried setting `SWIFT_VERSION`?
[version-swift](https://stackoverflow.com/questions/46338588/xcode-9-swift-language-version-swift-version)
