### ISSUE TITLE
App Permission

### ISSUE THREAD

**Issue by eagerashwani** [Apurv2017/audioRecorder2#8]
Everything works fine, but the app permission dialogs not appeared when the app opens. 
Permission allowed externally.

**Comment by apurvh** [comment]
yeah that's a issue with original plugin too, try permissions plugin for andriod, (for ios its not a issue)

**Comment by apurvh** [comment]
maybe someone can submit PR

**Comment by eagerashwani** [comment]
### _Thanks****_
